siteTitle = "Aftab Alam - fine web craftsmaship, since summer'o 2010"
siteDescr = "engineering fine web, since summer'o 2010"
siteDesc = "Full-stack Web Engineer. Javascript Fanboy. Perpetual Learner."
siteAuthor = "Aftab Alam"
siteAuthorCurr = "currently, @proptiger @makaan"

siteTwitterUrl = "https://twitter.com/aftabbuddy"
siteGithubUrl = "https://github.com/one-aalam"
siteEmailUrl = "mailto:one@aalam.in"
siteLinkedinUrl = "https://in.linkedin.com/in/oneaalam"

googleAnalyticsId = ""

linkPrefix = ""