siteTitle = "Blog by Aftab"
siteDescr = "Lorem Ipsum is simply dummy text of the printing and typesetting industry."
siteAuthor = "Aftab Alam"

siteTelegramUrl = "#"
siteTwitterUrl = "#"
siteGithubUrl = "#"
siteEmailUrl = "#"
siteRssUrl = "#"
siteVkUrl = "#"

googleAnalyticsId = ""

linkPrefix = "/gatsby-starter-lumen"